# MySQL
mysql:
  basic:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/basic?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com
  file:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/file??serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com