server:
  port: 4399

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.221.27.253:3306/basic?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 2762581@com
#  redis:
#    host: 124.221.27.253
mybatis-plus:
#  type-aliases-package: com.demo.pojo # 类别名包扫描
  configuration:
#    call-setters-on-nulls: true   # 当查询到的字段为空是,是否调用set方法对属性进行Null值的初始化
#    local-cache-scope: session  # 默认为session级别缓存,STATEMENT:关闭一级缓存
#    cache-enabled: true   #是否开启二级缓存,默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO


multi:
  dataSourceTemplateList:
    - dataSourceName: test1
      mapperScanPackage: com.test.mapper.test1
      resourcesPath:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
    - dataSourceName: test2
      mapperScanPackage: com.test.mapper.test2
      resourcesPath:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
    - dataSourceName: test3
      mapperScanPackage: com.test.mapper.test3
      resourcesPath:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test3?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com