spring:
  rabbitmq:
    host: 192.168.110.130 # IP
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: root
    password: root
    listener:
      simple:
        prefetch: 1 # 每次从消息队列拿到消息的数量