server:
  port: 4399

spring:
  redis:
    cluster:
      nodes: 10.211.55.55:32182
    password: 2762581
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.27.253:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: false   # 当查询到的字段为空是,是否调用set方法对属性进行Null值的初始化
    local-cache-scope: STATEMENT  # 默认为session级别缓存,STATEMENT:关闭一级缓存
    cache-enabled: false   #是否开启二级缓存,默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO
    db-config:
      logic-delete-value: 1 # 全局逻辑删除状态值
      logic-not-delete-value: 0 # 全局非逻辑删除状态值
  type-handlers-package: com.core.handle # 处理器扫描

multi:
  datasource:
    - driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
      mapper-scan: com.test.mapper.test
      name: test
    - driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
      mapper-scan: com.test.mapper.test2
      name: test2