server:
  port: 4399

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.27.253:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO