server:
  port: 8012
spring:
  application:
    name: code-generator
  datasource:
    url: jdbc:mysql://124.221.27.253/basic?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 2762581@com
    driver-class-name: com.mysql.cj.jdbc.Driver