server:
  port: 8088
spring:
  main:
    banner-mode: off
  application:
    name: gateway # 服务名称
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/basic/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
    sentinel:
      eager: true
      transport:
        dashboard: ${sentinel.dashboard.url}

logging:
  level:
    org.springframework.cloud.gateway: info