server:
  port: 8088
spring:
  application:
    name: Gateway # 服务名称
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: basic-service
          uri: lb://basic
          predicates:
            - Path=/basic/**
    sentinel:
      eager: true
      transport:
        dashboard: ${sentinel.dashboard.url}

logging:
  level:
    org.springframework.cloud.gateway: debug