# web port
server:
  port: 8811
# no web
#spring.main.web-environment=false

# log config
logging:
  config:
    classpath: log4j2.xml
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.27.253:3306/basic?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8810/job # 控制台地址
    accessToken: default_token
    executor:
      appname: executor # 执行器名称
      address:
      ip:
      port: 9999 # 注册端口
      logpath: /Users/maplej/App/JavaProject/SpringCloud/xxl-job/xxl-job-executor/logs
      logretentiondays: 30

mybatis-plus:
  mapper-locations: classpath:/Mapper/*Mapper.xml
  type-aliases-package: com.service.basic.doMain # 类别名包扫描
  configuration:
    call-setters-on-nulls: false   # 当查询到的字段为空是,是否调用set方法对属性进行Null值的初始化
    local-cache-scope: STATEMENT  # 默认为session级别缓存,STATEMENT:关闭一级缓存
    cache-enabled: false   #是否开启二级缓存,默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO
    db-config:
      logic-delete-value: 1 # 全局逻辑删除状态值
      logic-not-delete-value: 0 # 全局非逻辑删除状态值
  type-handlers-package: com.core.handle # 处理器扫描


