server:
  port: 8802
  servlet:
    context-path: /basic
spring:
  application:
    name: basic # 服务名称
  datasource:
    driver-class-name: ${mysql.basic.driver}
    url: ${mysql.basic.url}
    username: ${mysql.basic.username}
    password: ${mysql.basic.password}
#  cloud:
#    sentinel:
#      eager: true
#      transport:
#        dashboard: ${sentinel.dashboard.url}

mybatis-plus:
  mapper-locations: classpath*:/Mapper/*Mapper.xml
  type-aliases-package: com.demo.DoMain # 类别名包扫描
  configuration:
    call-setters-on-nulls: false   # 当查询到的字段为空是,是否调用set方法对属性进行Null值的初始化
    local-cache-scope: STATEMENT  # 默认为session级别缓存,STATEMENT:关闭一级缓存
    cache-enabled: false   #是否开启二级缓存,默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO

logging:
  level:
    cn.itcast: info
    org.springframework: info