spring:
  application:
    name: basic
multi:
  datasource:
    - driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
      mapper-scan: com.test.mapper.test1
      xml-scan:
      name: test1
    - driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.27.253:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2762581@com
      mapper-scan: com.test.mapper.test1
      xml-scan:
      name: test2