spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.111:8848 # nacos服务地址
  elasticsearch:
    username: "elastic" # 登录es的帐号
    password: "elastic" # 登录es的密码
    uris: "http://192.168.111.111:9200" # es路径
    connection-timeout: 2s
    socket-timeout: 2s

